---

- name: Restart PowerDNS
  service:
    name: "{{ pdns_service_name }}"
    state: restarted
    daemon_reload: "{{ (ansible_service_mgr == 'systemd') | ternary(true, omit) }}"
    # the sleep is needed to make sure the service has been
    # correctly started after being stopped during restarts
    sleep: 1
  when:
    - not pdns_disable_handlers
